### ISSUE TITLE
Redundant `#ifndef` in libccc.h

### ISSUE THREAD

**Issue by Yanis-F** [LexouDuck/libccc#35]
In `hdr/libccc.h` every time a header is included to get the type it defines, the include is wrappend in a ifndef like so: 
```c
#ifndef __LIBCCC_BOOL_H
#include "libccc/bool.h"
#endif
```
however, each of these header are alreade entirely wrappend in an `#ifndef __LIBCCC_[type]_H`. So the ifdnef in libccc.h are redundant and should be removed for clarity

**Comment by LexouDuck** [comment]
done, via e37b1edb88e4309274413975f581420ec7d756f7

It seems that everything in the CI routines is building perfectly fine without these, so it does seem like you are indeed correct, these were useless redundant include-guards.
