### ISSUE TITLE
StringArray extra functions

### ISSUE THREAD

**Issue by Fulguritude** [LexouDuck/libccc#7]
Add a string array "find" family of functions.
Add ideas to this thread.

=> Find and return index
=> Find and return char** of strarr+i

**Comment by Fulguritude** [comment]
StringArray_Reduce (takes a function pointer that reads a string and returns a bool)
StringArray_Insert (and InPlace version)

**Comment by LexouDuck** [comment]
These functions (and many many others) have been added via commits:
- 98bb6e7178ed5d4a42e778d6e3b465c1597e600e
- 391b8a68219a5332af546e0f9f074abc123dfad0
- c102093da7231cb621375995263bd4ed073b0fae
- 9a76e1738a9e6c13e16f090ea356cf467128cd46
